name: Fen
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: ^1.1.0
  fancy_drawer: ^1.0.0
  expansion_tile_card: ^1.1.0
  sleek_circular_slider: ^1.1.0
  spear_menu: ^0.0.2
  getwidget: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  simple_animations: ^2.2.1
  page_transition: ^1.1.6
  flutter_polyline_points: ^0.2.2
  geolocator: ^5.3.2+2
  google_maps_flutter:
  http: ^0.12.2
  after_layout: ^1.0.7
  cached_network_image: ^2.0.0
  sliding_sheet: ^0.3.7
  carousel_slider: ^1.4.1
  cloud_firestore: ^0.12.6
  firebase_auth: ^0.16.1
  fluttertoast: ^3.1.3
  intl: ^0.15.8
  flutter_local_notifications:
  auto_size_text: ^2.1.0
  pin_entry_text_field:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/assets/light_map.json
    - lib/assets/icons/
    - lib/assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Cairo-Regular.ttf
